#!/usr/bin/env bash

case "$1" in
    lock)
        swaylock
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        systemctl suspend && swaylock
        ;;
    hibernate)
        systemctl hibernate && swaylock
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
